export enum ErrorMessage {
    SERVER_ERROR = 'Server error occurred',
    USER_NOT_FOUND = 'User not found',
    NOT_FOUND = 'The item not found',
    NO_ACCESS = 'You don\'t have enough permission to perform this operation',
    PASSWORD_NO_MATCH = 'Password does not match place confirm and try again',
    PASSWORD_INVALID = 'You have supplied an invalid password',
    ROLE_EXIST = 'User already has this role',
    ROLE_NOT_EXIST = 'Role doesn\'t exist',
    USERNAME_TAKEN = 'The username already exist',
    PHONE_NUMBER_TAKEN = 'The Phone number already exist',
    REFRESH_TOKEN_NOT_FOUND = 'Refresh token not found',
    TOKEN_INVALID = 'You supplied an invalid token',
    USER_STILL__IN_SESSION = 'You are already in a session please clear all session',
    INVALID_USER_CREDENTIALS = 'Username or password doesn\'t match',
    EMPTY_DATA = 'You have sent empty data',

    ADDRESS_NOT_FOUND = 'Address not found',
    ADDRESS_NO_ACCESS = 'You don\'t have enough permission to access this address',
    ADDRESS_PRIMARY_DELETE = 'Cannot delete primary address. Please set another address as primary first.',
    ADDRESS_ALREADY_PRIMARY = 'Address is already set as primary',
    NO_PRIMARY_ADDRESS = 'No primary address found for this user',
    ADDRESS_ALREADY_EXISTS = 'This address already exists for this user',
}