export type RequestRow = {
    Customer: string;
    Location: string;
    PhoneNumber: string;
    Email: string;
    Status: "Active" | "Inactive" | "New";
    Currency: string;
    Collections: number;
    Earnings: "Loss" | "Gains";
    Action: string;
};

export const RequestsData: RequestRow[] = [
    {
        Customer: "John Doe",
        Location: "a house",
        PhoneNumber: "+ (123) 456 - 890",
        Email: "something@gmail.com",
        Status: "New",
        Currency: "CAD",
        Collections: 100000000,
        Earnings: "Gains",
        Action: "View More",
    },
    {
        Customer: "Sam Doe",
        Location: "a house",
        PhoneNumber: "+ (123) 456 - 890",
        Email: "something@gmail.com",
        Status: "Inactive",
        Currency: "CAD",
        Collections: 34,
        Earnings: "Loss",
        Action: "View More",
    },
    {
        Customer: "Jimmy Bob",
        Location: "a country",
        PhoneNumber: "+ (123) 456 - 890",
        Email: "something@gmail.com",
        Status: "Active",
        Currency: "CAD",
        Collections: 0,
        Earnings: "Gains",
        Action: "View More",
    },
    {
        Customer: "Bob Bob",
        Location: "a country",
        PhoneNumber: "+ (123) 456 - 890",
        Email: "something@gmail.com",
        Status: "Active",
        Currency: "CAD",
        Collections: 1110,
        Earnings: "Gains",
        Action: "View More",
    },
    {
        Customer: "Jimmy Bob",
        Location: "a country",
        PhoneNumber: "+ (123) 456 - 890",
        Email: "something@gmail.com",
        Status: "New",
        Currency: "CAD",
        Collections: 200,
        Earnings: "Gains",
        Action: "View More",
    },
    {
        Customer: "Sara Someone",
        Location: "a country",
        PhoneNumber: "+ (123) 456 - 890",
        Email: "something@gmail.com",
        Status: "Inactive",
        Currency: "CAD",
        Collections: 231,
        Earnings: "Loss",
        Action: "View More",
    },
    {
        Customer: "Sara Someone",
        Location: "a country",
        PhoneNumber: "+ (123) 456 - 890",
        Email: "something@gmail.com",
        Status: "Inactive",
        Currency: "CAD",
        Collections: 231,
        Earnings: "Loss",
        Action: "View More",
    },
    {
        Customer: "Sara Someone",
        Location: "a country",
        PhoneNumber: "+ (123) 456 - 890",
        Email: "something@gmail.com",
        Status: "Inactive",
        Currency: "CAD",
        Collections: 231,
        Earnings: "Loss",
        Action: "View More",
    },
    {
        Customer: "Sara Someone",
        Location: "a country",
        PhoneNumber: "+ (123) 456 - 890",
        Email: "something@gmail.com",
        Status: "Inactive",
        Currency: "CAD",
        Collections: 231,
        Earnings: "Loss",
        Action: "View More",
    },
    {
        Customer: "Sara Someone",
        Location: "a country",
        PhoneNumber: "+ (123) 456 - 890",
        Email: "something@gmail.com",
        Status: "Inactive",
        Currency: "CAD",
        Collections: 231,
        Earnings: "Loss",
        Action: "View More",
    },
    {
        Customer: "Sara Someone",
        Location: "a country",
        PhoneNumber: "+ (123) 456 - 890",
        Email: "something@gmail.com",
        Status: "Inactive",
        Currency: "CAD",
        Collections: 231,
        Earnings: "Loss",
        Action: "View More",
    },
    {
        Customer: "Sara Someone",
        Location: "a country",
        PhoneNumber: "+ (123) 456 - 890",
        Email: "something@gmail.com",
        Status: "Inactive",
        Currency: "CAD",
        Collections: 231,
        Earnings: "Loss",
        Action: "View More",
    },

];